imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    translator:      { fallback: test }
    default_locale: test

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     %kernel.root_dir%/cache/test.db
        memory:   false
        charset:  UTF8