dispatch_dashboard:
    resource: "@SGSAppBundle/Controller/Dispatch/DashboardController.php"
    type: annotation

dispatch_login_check:
    pattern:   /dispatch/login_check

dispatch_login:
    resource: "@SGSAppBundle/Controller/Dispatch/LoginController.php"
    type: annotation

agent_dashboard:
    resource: "@SGSAppBundle/Controller/Agent/DashboardController.php"
    type: annotation

agent_login_check:
    pattern:   /agent/login_check

agent_login:
    resource: "@SGSAppBundle/Controller/Agent/LoginController.php"
    type: annotation