dispatch_dashboard:
    resource: "@SGSAppBundle/Controller/Dispatch/DashboardController.php"
    type: annotation

dispatch_login_check:
    pattern:   /dispatch/login_check

dispatch_login:
    resource: "@SGSAppBundle/Controller/Dispatch/LoginController.php"
    type: annotation

agent_dashboard:
    resource: "@SGSAppBundle/Controller/Agent/DashboardController.php"
    type: annotation

agent_login_check:
    pattern:   /agent/login_check

agent_login:
    resource: "@SGSAppBundle/Controller/Agent/LoginController.php"
    type: annotation

request_dashboard:
    resource: "@SGSAppBundle/Controller/Request/DashboardController.php"
    type: annotation

request_login_check:
    pattern:   /request/login_check

request_login:
    resource: "@SGSAppBundle/Controller/Request/LoginController.php"
    type: annotation

admin_dashboard:
    resource: "@SGSAppBundle/Controller/Admin/DashboardController.php"
    type: annotation

admin_login_check:
    pattern:   /admin/login_check

admin_login:
    resource: "@SGSAppBundle/Controller/Admin/LoginController.php"
    type: annotation