dispatch_dashboard:
    resource: "@SGSAppBundle/Controller/Dispatch/DashboardController.php"
    type: annotation

dispatch_login_check:
    pattern:   /dispatch/login_check

dispatch_login:
    resource: "@SGSAppBundle/Controller/Dispatch/LoginController.php"
    type: annotation