dispatch:
    resource: "@SGSAppBundle/Controller/Dispatch"
    type: annotation
    prefix: /dispatch

dispatch_login_check:
    pattern:   /dispatch/login_check

agent:
    resource: "@SGSAppBundle/Controller/Agent"
    type: annotation
    prefix: /agent

agent_login_check:
    pattern:   /agent/login_check

request:
    resource: "@SGSAppBundle/Controller/Request"
    type: annotation
    prefix: /request

request_login_check:
    pattern:   /request/login_check

admin:
    resource: "@SGSAppBundle/Controller/Admin"
    type: annotation
    prefix: /admin

admin_login_check:
    pattern:   /admin/login_check