jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        SGS\Model\User: sha512

    providers:
        database:
            entity: { class: Model:User, property: email }

    access_control:
        - { path: ^/dispatch/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dispatch, roles: TYPE_DISPATCHER }

    role_hierarchy:

    firewalls:
        dispatch_login:
            pattern: ^/dispatch/login$
            anonymous: ~
        dispatch:
            pattern: ^/dispatch
            form_login:
                login_path: /dispatch/login
                check_path: /dispatch/login_check

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false