jms_security_extra:
    secure_all_services: false
    expressions: true

security:

    access_decision_manager:
        strategy:             unanimous

    encoders:
        SGS\Model\User: sha512

    providers:
        database:
            entity: { class: Model:User, property: email }

    access_control:
        - { path: ^/dispatch/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dispatch, roles: TYPE_DISPATCHER }
        - { path: ^/agent/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/agent, roles: TYPE_AGENT }

    role_hierarchy:

    firewalls:
        dispatch_login:
            pattern: ^/dispatch/login$
            anonymous: ~
        dispatch:
            access_denied_url: /dispatch/denied
            pattern: ^/dispatch
            form_login:
                login_path: /dispatch/login
                check_path: /dispatch/login_check
                username_parameter: _email
                default_target_path: /dispatch

        agent_login:
            pattern: ^/agent/login$
            anonymous: ~
        agent:
            access_denied_url: /agent/denied
            pattern: ^/agent
            form_login:
                login_path: /agent/login
                check_path: /agent/login_check
                username_parameter: _email
                default_target_path: /agent

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false