jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        SGS\Model\User: sha512

    providers:
        in_memory:
            memory:

    access_control:

    role_hierarchy:

    firewalls:
        dispatch:
            pattern: ^/dispatch
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false